-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.119.6.36;service_name=orcl;port=1521

SET client_encoding TO 'UTF8';

SET search_path = hr,public;
DROP TRIGGER IF EXISTS update_job_history ON employees CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_update_job_history() RETURNS trigger AS $BODY$
BEGIN
  CALL add_job_history(OLD.employee_id, OLD.hire_date, LOCALTIMESTAMP,
                  OLD.job_id, OLD.department_id);
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_update_job_history() FROM PUBLIC;

CREATE TRIGGER update_job_history
	AFTER UPDATE OF job_id,department_id ON employees FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_update_job_history();

